# ignore .build folder


disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - force_unwrapping

excluded:
  - Pods
  - Carthage
  - "**/.build/**"
  - "Source/Core/.build/**"

line_length:
  warning: 120
  error: 200

force_unwrapping: error

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 15
